### ISSUE TITLE
Make `useQuery` with `suspense: true` to return non-nullable `data`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1354]
### Describe the feature you'd like to request

`{ suspense: true }` should let us use `data` without checking its integrity.

We can use `suspense: true` in SSR now, see #3130

### Describe the solution you'd like to see

Given

```ts
const postQuery = trpc.post.byId.useQuery({ id }, { suspense: true });
```

`postQuery.data` should be **not** be nullable.

Considerations: if `enabled: true`, we should not infer it as non-nullable

### Desribe alternate solutions

- Default options to set `suspense: true`
- Add a `useSuspenseQuery` / `useSuspenseInfiniteQuery`

Another approach would be to enable this behavior globally when creating the react-query hooks.

```tsx
export trpc = createTRPCReact<Context>({suspense: true})
```

### Additional information

- `enabled:` `true`/`false` should still work
- We need to narrow the generic so we still can't pass extra params to `opts`

**Comment by hugues-m** [comment]
Maybe this will be useful to somebody :
I also wanted to enable suspense globally without using the second arguments in every use 

```ts
const rpc = createReactQueryHooks<AppRouter>()

export const useQuery: typeof rpc.useQuery = (pathAndInput, opts) =>
  rpc.useQuery(
    pathAndInput,
    // Add suspense by default. Can be overriden with useQuery(..., {suspense: false})
    opts ? { suspense: true, ...opts } : { suspense: true },
  )
```

**Comment by iway1** [comment]
Should we be encouraging the use of `suspense` with tRPC? Seems like a horribly costly footgun.

The way react query works with suspense, any time there are multiple queries in the same component it creates a waterfall. The first query will block the next query, which blocks the next query, ETC. 

So it can seriously delay the requesting of required data for basically no reason at all any time we have multiple independent queries in the same component like:

```jsx
function ComponentWrappedWithSuspense() {
    const queryOne = useQuery(['someEndpoint']);
    const queryTwo = useQuery(['someOtherEndpoint']); // won't start until queryOne finishes.
    // ...
}
```
We could in theory have multiple suspended components some of the time, I suppose, but that seems like extra work. Plus, I'd think that most people aren't going to know that they need to do that and could easily make this mistake.

In tRPC, in most React apps, it is probably going to be quite common to have multiple queries, so it'd be an easy mistake for people to make. Here's a code sandbox showing the issue (check the console and refresh): https://codesandbox.io/s/mystifying-meadow-n289qh?file=/src/App.js:666-1053

**Comment by leafyshark** [comment]
I assume the `{ suspense: true; }` flag is still a WIP. With the way things are going with React, we should definitely consider the use of suspense as @iway1 mentioned above.

**Comment by KATT** [comment]
What @iway1 is describing could be circumvented by:

- Splitting the queries into different components
- Adding support for `useQueries()`

**Comment by iway1** [comment]
> Splitting the queries into different components

@KATT I don't think this is a viable solution in practice because (1) that's going to be more work for the developer and (2) would make it impossible to create certain types of user interfaces. 

I guess (2) is more important. The issue is that we'd be forced to create multiple `<Suspense/>`  components each with their own fallback and wouldn't be able to create a single fallback with multiple queries. 

It's not uncommon to have some piece of UI wait for data from multiple requests before showing that piece of UI, and to show the same common fallback when *either* of the queries are loading (which means we're forced to have each query within the same suspense component).

In such situations, we either don't use suspense or we have a request waterfall. I think mix and matching `suspense: true` and `suspense: false` is also probably bad practice because of lack of consistency within a codebase.

So, yeah, `suspense: true` simply doesn't cover all use cases, and I stand by the idea that it can easily make the user experience worse if the developer doesn't know how it works with `react-query`.

> Adding support for useQueries()

This would be great! This would solve the problem. I would probably switch to `<Suspense/>` if we had `useQueries`, personally. And if we could figure out the typescript magic to have it return non-nullable data as well that would really great.

**Comment by KATT** [comment]
I definitely want this ASAP.

I have started using suspense in my app now as server-side suspense now works.

**Comment by KATT** [comment]
Adding an experimental `.useSuspenseQuery()`-hook in #3137 that can be enabled if you look closely at it
