### ISSUE TITLE
Add note about strict mode in docs

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#1506]
Gotten a few questions like this https://github.com/trpc/trpc/discussions/1500

Should probably be in several installation sections

**Comment by ahhshm** [comment]
I think Zod should be removed from some of the installation guides. For example, in the next.js one, you installed Zod but never actually used it. the same thing happens in the react.js guide. Here is my plan to fix this:
1. creating a new section just about input validation. here we can give a detailed description of each validation library.
2. referencing anywhere we are dealing with input validation to that section.
3. adding a little warning about Zod anywhere we are using it.

If you agree I can do it.

**Comment by sachinraja** [comment]
> I think Zod should be removed from some of the installation guides

I disagree. I'd rather have a little duplication across installation guides than links in each of them to different sections. I would consider it a nicer user experience to just have everything in one section.

> creating a new section just about input validation. here we can give a detailed description of each validation library.

I don't think this is a good idea. Zod is great, and I'd rather have everyone converge on one input validation library. This can also help when creating 3rd party packages because you only have to handle one validation library. An example of this is https://github.com/sachinraja/trpc-playground, which uses the Zod schemas to produce TypeScript types. This would be much more difficult if I wanted to implement type generation for other input validation libraries.

> adding a little warning about Zod anywhere we are using it.

I think this is a good idea, but I think it should be more prominent than a warning. Maybe configuring `tsconfig.json` should be written as an actual step in the guides.
