### ISSUE TITLE
Add a default retry handling to avoid retry on specific TRCP errors

### ISSUE THREAD

**Issue by ArnaudBarre** [trpc/trpc#1714]
I just found that with default settings when using the react client, the query is retried 3 times despite the server sending an `UNAUTHORIZED` error. I think a default could be to only retry in this cases:

PARSE_ERROR: false
BAD_REQUEST: false
INTERNAL_SERVER_ERROR: ?
UNAUTHORIZED: false
FORBIDDEN: false
NOT_FOUND: false
METHOD_NOT_SUPPORTED: false
TIMEOUT: true
PRECONDITION_FAILED: false
PAYLOAD_TOO_LARGE: false
CLIENT_CLOSED_REQUEST: true

I can create a PR if you agree on the general idea

**Comment by KATT** [comment]
I think I don't want it in the _library_, but I want the examples to showcase a production-ready version, so it would be good to have some more sensible defaults in here: https://github.com/trpc/trpc/blob/main/examples/next-prisma-starter/src/pages/_app.tsx#L74

**Comment by ViktorQvarfordt** [comment]
The default behavior of retrying on error is strange to me. Most errors don't resolve automatically. The only error I can think of that should be retried is if the network connection was interrupted.

The current mechanism is problematic for a user since they have to wait for all retries to fail until the app can show the error. This is clearly not desired for errors like 400 Bad request, 401 Unauthorized, 404 Not found. In these cases, we'd rather show the user directly what the problem was so that they can fix it.

**Comment by ViktorQvarfordt** [comment]
Is it possible to completely disable the retry mechanism until something more flexible is put in place?

**Comment by KATT** [comment]
See the message above, you can customize the behavior fully

**Comment by ArnaudBarre** [comment]
Yes it's easy do disable react-query behaviour. For now I ended up using: 
```ts
new QueryClient({ defaultOptions: { queries: { retry: false } } })
```
