### ISSUE TITLE
TypeError: can't access property "items", batchCopy is null

### ISSUE THREAD

**Issue by zomars** [trpc/trpc#2008]
I was fiddling with request batching and  [setting a maximum batch](https://trpc.io/docs/links#setting-a-maximum-batch-size) size started to throw this error:

![imagen](https://user-images.githubusercontent.com/3504472/174388841-8d375f38-87a2-4cc1-8f2b-e0e35abecaf6.png)

This is our tRPC config BTW:

![imagen](https://user-images.githubusercontent.com/3504472/174389074-de7875cb-328d-4130-8672-86c5f9ba93b0.png)

**Comment by KATT** [comment]
Can you do provide a draft PR with a step to reproduce? Since y'all are oss is should be easy

**Comment by zomars** [comment]
Sure @KATT tagged you in [this PR](https://github.com/calcom/cal.com/pull/3087). I've commented out the lines that [enables batch size here](https://github.com/calcom/cal.com/pull/3087/files#r900468816). Just uncomment it and try to go to a user booking page like `pro/30-min`

**Comment by KATT** [comment]
Unable to reproduce, see #2013 and feel free to play with it.

To start the repo


```
yarn
yarn dev
```

to start test:

```
yarn test --testPathPattern dataloader --watch
```

**Comment by zomars** [comment]
I think the culprit is the quantity of the data returned more than the number of calls

**Comment by KATT** [comment]
We don't have time to debug this further & it's a feature that's getting removed soon, maybe if you can get Cal to sponsor tRPC we can prioritize it higher 😜

**Comment by KATT** [comment]
No reproduction is supplied and the feature is going out soon.

Feel free to pick up #2013 and make a failing test and we'll fix it.

**Comment by relm923** [comment]
@KATT I'm pretty sure this edge occurs when the last batch loaded exceeds the `maxBatchSize` as 2 `dispatch` calls will be executed.

1. https://github.com/trpc/trpc/blob/main/packages/client/src/internals/dataLoader.ts#L80
2. https://github.com/trpc/trpc/blob/main/packages/client/src/internals/dataLoader.ts#L86

The first `dispatch` destroys pending timers and then immediately afterwards a new timeout dispatch is queued up. The second one fails because `batch` has already been reset to `null`.

I'll take a stab at updating the test case

**Comment by relm923** [comment]
Now with repo test - https://github.com/trpc/trpc/pull/2484
