### ISSUE TITLE
Add minimal Fresh example?

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2117]
https://fresh.deno.dev/

**Comment by KATT** [comment]
@sachinraja WDYT? It would also help validate that we don't break ESM support etc

**Comment by sachinraja** [comment]
I tried it before but Deno/esm.sh sucks with many peerDependencies. This issue is made worse because alpha versions can't use semver. I'll have another go and see how it is though.

**Comment by bartlomieju** [comment]
Hi, Bartek from the Deno team here. I'd love to help out in any way possible to get TRPC running in Deno. Are there any immediate blockers that we could tackle? We are still working on improving `deno_std/node/` which is a Node compatibility layer that esm.sh uses. Or maybe there are some changes need to esm.sh itself that could unblock this integration?

**Comment by sachinraja** [comment]
Hey @bartlomieju, tRPC v10 is decoupled from Node already runs in Deno! I have an example with Ultra [here](https://github.com/sachinraja/trpc-ultra). What could be better is esm.sh's handling of `peerDependencies` which [can break types](https://github.com/ije/esm.sh/issues/333) and forces me to use a[ crazy import map](https://github.com/sachinraja/trpc-ultra/blob/main/importMap.json#L13). tRPC existing primarily in the Node/Node resolution ecosystem means we rely on `peerDependencies` often in core packages and third-party integrations.

I think there are some other issues but it's been a while since I've played around with it so I'd have to look into them again. Thanks, glad to have your support here!

**Comment by bartlomieju** [comment]
@sachinraja thanks for the information. Let me know if the problem with esm.sh persists after posting a tag, in such case we will look into it.

**Comment by LunaTK** [comment]
Hi!
I was able to make a minimal example, wish it helps you 🤞

https://github.com/LunaTK/fresh-trpc-example

**Comment by sachinraja** [comment]
Nice work on that, it looks great @LunaTK! Please make a PR to add this to https://trpc.io/docs/awesome-trpc (on the `next` branch) and I think we can close this.
