### ISSUE TITLE
Add a `/merch`-part on the website? :)

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2180]
https://twitter.com/alexdotjs/status/1538472230505652225

- Anything that would be embeddable with an iframe or something easy would be nice.
- Stuff like t-shirts and stickers should have the same provider
- Ship globally, but ideally that they are _produced_ locally

**Comment by Nsttt** [comment]
Good idea ! You can probably use [Hydrogen](https://hydrogen.shopify.dev/) from the Shopify team.

Heard you can make cool stuff on it with ease.

**Comment by KATT** [comment]
Too much work, I just want a script tag or something that I can add to docusaurus

**Comment by carstenlebek** [comment]
The Shopify buy button is probably the easiest way to do this, if you want to go with Shopify (what I would recommend, because most print on demand suppliers have integrations).

[Shopify buy button](https://apps.shopify.com/buy-button?locale=de&surface_detail=buy+button&surface_inter_position=1&surface_intra_position=1&surface_type=search)
