### ISSUE TITLE
remove initTRPC double function call

### ISSUE THREAD

**Issue by josvanos** [trpc/trpc#2595]
### Describe the feature you'd like to request

I have always the feeling while editing /reading / writing the docs, (syntax) pain points arise. I was reading the migration guide and found this section
```ts
import { initTRPC } from '@trpc/server';

// Beware of the double `()()`
export const t = initTRPC()();
```
The comment already calls out this syntax is unfavourable (not obvious/ naturally) . I also dislike the syntax, because the function says nothing about what the input is for the first and second function.  In the example below, why couldn't the error formatter in the first one?.

```ts
export const t = initTRPC<{
  ctx: Context;
}>()({
  // Optional:
  transformer: superjson,
  // Optional:
  errorFormatter({ shape }) {
    return {
      ...shape,
      data: {
        ...shape.data,
      },
    };
  },
});
```
*That you also need to put in the context type makes even more difficult* 

### Describe the solution you'd like to see

In general, I think tRPC is missing a config server side. I propose two solutions as alternative:

```ts
// I looked into the source code  and the first function has zero params (?)
// TRPC exported function
const defineConfig = (config) => initTRPC()(config)

import { defineConfig, initTRPC } from "@trpc/server"; // defineConfig is more from the vue / vite landscape.
export const t = defineConfig() 

// for TRPC  the following names are maybe more correct:  
export const t = defineAppRouter(); 
export const t = defineBaseRouter(); 

```
After inspecting the source code I believe this syntax is possible. This would also improve the docs/ learning curve (one documentation page could explain all configurations of TRPC) 

Option 2: change docs only (change trpcInner to a meaningful function name)
```ts
const trpcInner = initTRPC(); 
export const t =  trpcInner();
```
You could also take it one step further and create it as express app.
```ts
const trpc = initTRPC();

// custom methods to use on trpc 
trpc.onError();
trpc.use();

export const t =  trpc.create(); 
```

### Desribe alternate solutions

current syntax

#### Food for thought:
- would it be nice to create a file convention like  `trpc.config.ts` or `trpc.router.ts` ?

#### Question:  
- is the style of the new client, `client.queries.getUsers()` or `client.getUsers.query()`? 

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
The first function call takes in the generics, the second one takes in the options. This is because TS won't let us partially infer the generics. So you'd have to pass in the types for the `errorFormatter` and `transformer` if you wanted to pass in any `Context` type.

> change docs only (change trpcInner to a meaningful function name)

I think it's easier to just accept the double function call. `trpcInner` would just be a useless variable and increase boilerplate.

> would it be nice to create a file convention like trpc.config.ts or trpc.router.ts ?

The examples follow conventions already.

> You could also take it one step further and create it as express app.

`@trpc/server` core is agnostic from Node, this is what adapters are for.

**Comment by mmkal** [comment]
Reopening this because I think there's further discussion to be had, and I don't want it to get lost on a closed thread (not implying it was closed improperly, I just have something I want to add).

@sachinraja @KATT what about naming two functions in some kind of logical way so there isn't this big gulf between users and implementers. Anyone new looking at `initTRPC()()` is going to get intimidated and probably put off. What about something like:

```ts
// initTRPC.ts
export interface TRPCBuilder<TParams extends Partial<InitGenerics>> {
    configure: <TNewParams extends TParams>() => TRPCBuilder<TNewParams>
    builder: <
        TOptions extends Partial<InitOptions<{
            ctx: TParams['ctx'] extends undefined ? {} : NonNullable<TParams['ctx']>;
            meta: TParams['meta'] extends undefined ? {} : NonNullable<TParams['meta']>;
        }>>
    >(options?: ValidateShape<TOptions, Partial<InitOptions<{
        ctx: TParams['ctx'] extends undefined ? {} : NonNullable<TParams['ctx']>;
        meta: TParams['meta'] extends undefined ? {} : NonNullable<TParams['meta']>;
    }>>> | undefined) =>  /* same as existing final return type of initTRPC */
}

export const trpc: TRPCBuilder<{}>
```

Usage:

```ts
import {trpc} from '@trpc/server'

const t = trpc.builder()

export const whatever = t.procedure
  .input(z.object({ foo: z.string() })
  .query(({ input }) => [input.foo])
```

Or with ctx/meta options:

```ts
import {trpc} from '@trpc/server'

const t = trpc.configure<{ ctx: { abc: number } }>().builder()

export const whatever = t.procedure
  .input(z.object({ foo: z.string() })
  .query(({ input, ctx }) => [input.foo, ctx.abc])
```

Not sure about the naming of either `.configure()` or `.builder()`.

Another option would be just to have two methods `.withContext<{ abc: number }>()` and `.withMeta<{ xyz: string }>()` which would add `ctx` and `meta` generics, respectively.

`.builder()` might not be the best name if `t` shouldn't be considered a builder. (If it isn't - what is it? I think it's important that it has some kind of English-language name, so people can communicate about it properly, since it's an important part of the design - in general I think we should show things we love them by naming them).

**Comment by KATT** [comment]
On one hand, I'm like _"meh, you do it once, who cares?"_, and on the other hand I think it's the first interaction you might have with tRPC and it is a bit counter-intuitive

How about the words `configure` & `create()` at the end?

```ts
import {trpc} from '@trpc/server'

const t = trpc.create();
const t = trpc.configure<{ ctx: {} } >().create()
```


Alternative, call it `generics()` or something?

```

```ts
import {trpc} from '@trpc/server'

const t = trpc.create();
const t = trpc.generics<{ ctx: {} } >().create()
```



We could even do it like it is now but with an extra helper, but it wrecks discoverability a bit:

```ts
import {initTRPC} from '@trpc/server'

const t = initTRPC();
const t = initTRPC.withGenerics<{ ctx: {} } >()()

```

**Comment by KATT** [comment]
I quite like the idea to make it a proper builder

```ts
const t = initTRPC
  .withMeta<{}>()
  .withContext<Context>()
  .create()
```

**Comment by josvanos** [comment]
One quick note I wanted to add to this discussion, I have the feeling this proposed builder pattern is way more resistant to future changes than current implementation `initTRPC()()`.  I forgot to address future changes in my first message.

About the builder pattern:  initTRPC is more a function name than an object name, rather just trpc or something like that.
I do not have a preference if it is `.setContext` or `.withContext` or `.useContext` or `.context` , as long as it is consistent.

**Comment by alexgraddev** [comment]
The new `satisfies` should help I think: https://github.com/microsoft/TypeScript/issues/47920

**Comment by sachinraja** [comment]
@mmkal Alex and I talked about this, and we're in favor of the builder pattern style (copying from above):
```ts
const t = initTRPC
  .meta<{}>() 
  .context<Context>()   // maybe `.ctx<Context>()`?
  .create()
```

I think this is better because it removes the object generic we had before, which was more confusing than the double call to me.

No expectations, but would you be willing to do a PR for this?

**Comment by mmkal** [comment]
Nice - yes I can open a pr. Have been looking for a chance to make a v10 change about this size.
