### ISSUE TITLE
[v10] feat: update `setupNext` to not include `proxy`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2607]
### Describe the feature you'd like to request

Right now we do 

```ts

export const trpc = setupTRPC<AppRouter>({
  config({ ctx }) {
    // [..]
  })
});
```

and we call it we use 

```ts
trpc.withTRPC(router)`
trpc.proxy.hello.useQuery(/* ... /*)
```

### Describe the solution you'd like to see

Change this to 

```ts

export const trpc = setupTRPC<AppRouter>({
  config({ ctx }) {
    // [..]
  })
});
```

and we call it we use 

```ts
trpc.withTRPC(router)`
trpc.hello.useQuery(/* ... /*)
```

(no `.proxy`)

### Desribe alternate solutions

n/a

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
I tried to do this before but it was slightly annoying do to how the internal `createProxy` works so I just left it alone. One issue is that `createProxy` works on `apply` (when the proxy is called like a  function) so any actual property (not a function) that we want to expose has to be wrapped in `new Proxy`. I think instead of the `createProxy` working on `apply`, we should return a function from `get`.
