### ISSUE TITLE
[idea] make distinction between queries & mutations optional

### ISSUE THREAD

**Issue by ollydixon** [trpc/trpc#2653]
### Describe the feature you'd like to request

Over the years of using GraphQL we always found that using query and mutation was pointless.
We just set all our quires to mutation.

We're using tRPC with the express plugin for a Flutter project, believe it or not is great tRPC even without the type completion is the best choice for any project; the tRPC playground gives great documentation.

One massive problem we have though is GET and POST requests from the mutation and query have different formats to get data.

So we set everything to POST with mutation and use body.

Perhaps removing query, or just naming everything with query is better?

Or maybe I'm wrong and you want to maintain GET for server logs? If that matters.

### Describe the solution you'd like to see

^^

### Desribe alternate solutions

^^

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by sachinraja** [comment]
You'd be better off using the [openapi integration](https://github.com/jlalmes/trpc-openapi). It's built for these situations and there's a lot of good tooling built around openapi too.

> Perhaps removing query, or just naming everything with query is better?

Queries are useful because they can easily be cached by CDNs. Caching for POST requests is more complicated. There are whole companies built around this for GraphQL (see [Stellate](https://stellate.co/)).

**Comment by ollydixon** [comment]
@sachinraja nah, OpenAPI has way too much boiler plate. Using the playrgound and just typing functions is much more fun/less verbose.

**Comment by ollydixon** [comment]
@sachinraja my first few minutes of using the OpenAPI thing (Just to see) and I get pointless errors like ```TRPCError: [query.health] - Input parser expects a Zod validator``` when there's no need to input validate this endpoint 😂

**Comment by ollydixon** [comment]
<img width="309" alt="Screenshot 2022-09-08 at 16 02 03" src="https://user-images.githubusercontent.com/6940726/189142427-2289b5a7-01be-49b8-b4c4-701278f5aab0.png">

<img width="513" alt="Screenshot 2022-09-08 at 16 02 00" src="https://user-images.githubusercontent.com/6940726/189142456-94171da8-6fb3-487c-9c96-a5860485c7b2.png">

Looks like it don't work; think I'll stick to the easy mode method I had before; the playground is too good for docs ❤️

**Comment by ollydixon** [comment]
Also Swagga 🤮

**Comment by jlalmes** [comment]
Hi @ollydixon, a lot to unpack here!

### Feature request: Remove queries!?

Removing `queries` because **you** don't use them is a pretty wild feature request. As @sachinraja mentioned there are a vast number of use-cases where `queries` are super useful, not to mention just having a split in the mental model where you can differenciate between reads & writes. (There was a great twitter thread about this but can't find it right now). 

> please don't open issues calling a feature pointless just because you aren't using it.

 It's not the first time you've made some weird remarks in issues/discussions on this repo, please be more considerate when participating in the future.

> We will go back to using Mutation for everything

Great! If this works for you, then this is what you should do.
 
 ### tRPC OpenAPI

> Looks like it don't work

I can ensure you that `trpc-openapi` does indeed work 🙃

It's quite clear that you've not even read the [Usage guide](https://github.com/jlalmes/trpc-openapi#usage) which is right at the top of the `README` so I don't have much sympathy for you here. Typically you'd expect a dev to read how something works before proclaiming that it's broken 🤷‍♂️

> I get pointless errors like TRPCError: [query.health] - Input parser expects a Zod validator when there's no need to input validate this endpoint 😂

We need an Zod `input` validator in order to generate an OpenAPI schema **even if no input is expected** (if you'd like to drop me a DM I'd happily talk you through the tRPC internals & why this is the case). 

You should just set `z.void()` if no input is expected (it says this in the `README`, if you'd decided to read it).

> <img alt="Screenshot 2022-09-08 at 16 02 03" width="309" src="https://user-images.githubusercontent.com/6940726/189142427-2289b5a7-01be-49b8-b4c4-701278f5aab0.png">
> 
> <img alt="Screenshot 2022-09-08 at 16 02 00" width="513" src="https://user-images.githubusercontent.com/6940726/189142456-94171da8-6fb3-487c-9c96-a5860485c7b2.png">

Again, you've not setup `trpc-openapi`, and you're expecting it to work!? This screenshot shows the correct behaviour. 

The function you're _probably_ looking for is `generateOpenApiDocument`. You can read how to use it in the [README](https://github.com/jlalmes/trpc-openapi/blob/master/README.md), but let's be honest, you probably won't will you?

> Also Swagga 🤮

😂😂😂 there are [many other options](https://letmegooglethat.com/?q=openapi+swagger+ui+alternatives). 


Not mega impressed by your attitude here @ollydixon, but this is the open-source in 2022 I guess...

**Comment by KATT** [comment]
Actually, I'm going to keep this open for a bit, I wna play around with something that might enable POST for everything for ppl who like that.

**Comment by KATT** [comment]
I had an idea the other week of potentially allowing some API that allows this for people who want it.

## Draft

### Server
```ts
// Instruct tRPC that we don't want the `query`/`mutation` distinction
const t = initTRPC.pureRPC().create();

// Procedures are defined with `.resolve` at the end rather than `.query`/`.mutation`
const appRouter = t.router()
  greeting: t.procedure.input(z.string().optional()).resolve((opts) => `Hello ${opts.input ?? 'World'}!`),
});

export type AppRouter = typeof appRouter;
```

### Raw client

```ts
// client.ts

const client = createTRPCProxyClient<AppRouter>({
  url: "..."
})

// Will be called with `()` in the client, will always do a `POST` request for HTTP
appRouter.greeting();
```

### React

```ts
const trpc = createTRPCReact<AppRouter>();

// both of these are OK
trpc.greeting.useQuery();
trpc.greeting.useMutation();
```

**Comment by KATT** [comment]
I don't know when/if I'll prioritize playing around with this myself as I do think the query/mutation distinction is useful & so does [most other people](https://twitter.com/alexdotjs/status/1528854148011130880).

**Comment by ollydixon** [comment]
I was drawn to this library cause of the simplicity. We use the playground as docs.

When you use both GET/POST with query/mutation with external projects, such as flutter apps need to define two fetch methods because the GET has no body but the POST does; it's two different formats.

Our fetch method as I mentioned above for Flutter just mentions the name of the function fetch('user.get-light', "someid"). This is super nice; but adding GET/POST here is in my option useless; what's the point?

We know what our functions return and input, we have list of them.

<img width="294" alt="Screenshot 2022-09-09 at 08 35 28" src="https://user-images.githubusercontent.com/6940726/189286971-4a1e9a32-3abb-4a66-a798-0163819c7102.png">

Example of an old GraphQL lib we have.
<img width="1438" alt="Screenshot 2022-09-09 at 08 38 33" src="https://user-images.githubusercontent.com/6940726/189287241-5db3cd4b-b6ad-4c79-b3bf-f19606a0d640.png">

Mutation only, what is the point of query. Totally useless to have that extra 'step'.
<img width="366" alt="Screenshot 2022-09-09 at 08 38 45" src="https://user-images.githubusercontent.com/6940726/189287250-2cc61882-7c70-4ebd-9de3-28bdcd3927de.png">

I know for the classic API users it might be a little hard abandon this concept; but let's move into a simpler future with tRPC!

**Comment by KATT** [comment]
The other thing with `GET` is that it's easy to cache on.

**Comment by ollydixon** [comment]
@KATT understandable; 
We've had platforms with billions of transactions; servers and requests are dirt cheap and even cheaper at scale; cache has only ever caused issues over the years; you don't need it!

Folks are obsessed with over caching everything 😂😂

**Comment by ollydixon** [comment]
@KATT for reference, API calls, database transactions and code is a really small resources, one image on your site is usually much larger! That's important to cache ya; not requests.

**Comment by ollydixon** [comment]
@jlalmes thanks for your input; I didn't mean to offend at all; I'm just a bit direct 😎

**Comment by KATT** [comment]
> @jlalmes thanks for your input; I didn't mean to offend at all; I'm just a bit direct 😎

@ollydixon, this wasn't the first time. Be respectful. Next time I'll ban you from the community.

**Comment by KATT** [comment]
Moving to #2663
