### ISSUE TITLE
feat: procedure paths with dots

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#2737]
Related: #2713

> In terms of the actual code. There is an edge-cases that I'd like us to consider:
> 
> When people use dot-notation in their procedure names, I am not sure if they should be split.
> 
> **Example:**
> 
> ```ts
> const router = t.router({
>   foo: t.router({
>     'bar.qux': t.procedure.query(() => 'hello'),
>   }),
> })
> ```
> 
> Should a call to `trpc.foo['bar.qux'].useQuery()` become:
> 
> - `['foo', 'bar', 'qux']` or
> - `['foo', 'bar.qux']`
> 
> I have yet to decide - WDYT @TkDodo?
> 
> _Originally posted by @KATT in https://github.com/trpc/trpc/pull/2711#pullrequestreview-1106976037_

**Comment by JonParton** [comment]
Just tagging [this comment (#2713) ](https://github.com/trpc/trpc/pull/2713#issuecomment-1246956147)  in here too.

It's worth bearing in mind that the actual tRPC server side seems to not distinguish between a procedure defined using `.` seperation in a procedure property name or the same defined as sub routers! 

It ignores the fact you defined it with the `.` in a single property name and joins it in with the rest of the path so that both ways of defining become `foo.bar.qux` as the path.
