### ISSUE TITLE
feat: Subscriptions heartbeat option

### ISSUE THREAD

**Issue by spiffytech** [trpc/trpc#2822]
### Describe the feature you'd like to request

Some providers (such as Fly.io) will automatically terminate websockets after some period of idleness (like 60 seconds).

Having TRPC constantly reconnect is unnecessary load on the server, and also on the client if stuff like `onStarted` logic is registered.

I suggest TRPC have an option to emit heartbeat messages over the websocket at a specified interval, to keep idle connections open.

### Describe the solution you'd like to see

Either the client or the server (I'm not sure which) would have an option to emit a heartbeat every N (configurable) seconds. An empty message, just enough to keep the websocket from being considered idle.

### Desribe alternate solutions

I'm working around this now with a subscription that just emits `null` every N seconds. It gets the job done, this just feels like something that would be good to have built-in.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

<sub>[T-72](https://linear.app/trpc/issue/T-72/feat-subscriptions-heartbeat-option)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/2822">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/2822/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/2822/pledge.svg">
</picture>
</a>

**Comment by KATT** [comment]
Cool! Could you make an API proposal? 

Ideally, we'd do this on the server and just have the clients somehow ignore this message.

Or should it do be a PING/PONG sort of thing? Server pings client and terminates the connection if it doesn't get a pong?

**Comment by sg-gdarnell** [comment]
The lack of a heartbeat/keep-alive bit me this week at work. Heroku will terminate connections it considers to be idle after 55 seconds (see https://devcenter.heroku.com/articles/error-codes#h15-idle-connection), so my tRPC connections are being terminated repeatedly, sometimes causing messages that would've otherwise been sent to be lost during the reconnect window.

For my use case a simple keep-alive or a ping/pong would be sufficient, especially if combined with a lazy disconnect (https://github.com/trpc/trpc/discussions/2672) and automatic reconnect (https://github.com/trpc/trpc/pull/2783). I took a crack at implementing ping/pong yesterday but I ran into some build issues. For now I'm just going to add a `ping` query to my router that returns `pong` and call it on an interval to avoid this problem.

Prior art in the GraphQL space:
[`subscriptions-transport-ws` had a configurable keep-alive](https://github.com/apollographql/subscriptions-transport-ws/blob/c6fb351fe3d7c7a447438798fab43c268b33036e/src/client.ts#L654-L667)

`graphql-ws` has configurable ping/pong: [server](https://github.com/enisdenjo/graphql-ws/blob/799cfc7bbe0f6d1a5c90b4880f02c58c5c3a06d4/src/use/ws.ts#L102-L124), [client](https://github.com/enisdenjo/graphql-ws/blob/799cfc7bbe0f6d1a5c90b4880f02c58c5c3a06d4/src/client.ts)

**Comment by garrettld** [comment]
The lack of a heartbeat/keep-alive bit me this week at work. Heroku will terminate connections it considers to be idle after 55 seconds (see https://devcenter.heroku.com/articles/error-codes#h15-idle-connection), so my tRPC connections are being terminated repeatedly, sometimes causing messages that would've otherwise been sent to be lost during the reconnect window.

For my use case a simple keep-alive or a ping/pong would be sufficient, especially if combined with a lazy disconnect (https://github.com/trpc/trpc/discussions/2672) and automatic reconnect (https://github.com/trpc/trpc/pull/2783). I took a crack at implementing ping/pong yesterday but I ran into some build issues. For now I'm just going to add a `ping` query to my router that returns `pong` and call it on an interval to avoid this problem.

Prior art in the GraphQL space:
[`subscriptions-transport-ws` had a configurable keep-alive](https://github.com/apollographql/subscriptions-transport-ws/blob/c6fb351fe3d7c7a447438798fab43c268b33036e/src/client.ts#L654-L667)

`graphql-ws` has configurable ping/pong: [server](https://github.com/enisdenjo/graphql-ws/blob/799cfc7bbe0f6d1a5c90b4880f02c58c5c3a06d4/src/use/ws.ts#L102-L124), [client](https://github.com/enisdenjo/graphql-ws/blob/799cfc7bbe0f6d1a5c90b4880f02c58c5c3a06d4/src/client.ts)

**Comment by KATT** [comment]
I think Heroku terminates **all connections** after a minute regardless?

**Comment by quolpr** [comment]
This will also fix websocket problems with ios safari https://github.com/enisdenjo/graphql-ws/discussions/290

**Comment by joanrieu** [comment]
There is a very simple workaround for this issue. The websocket tRPC server supports request batching, and by using the WSClient instance that you provide to wsLink, you can actually send an _empty_ batch, which is just `[]` sent on the websocket. The server will not answer anything. These two bytes are enough to keep the connection alive on Fly.io.

The interesting lines:

```ts
const client = createWSClient(...);
// ...
client.getConnection().send("[]");
```

Full example:

```ts
const client = createWSClient({
  url: '...',
});

export const trpc = createTRPCProxyClient<AppRouter>({
  links: [
    wsLink({
      client,
    }),
  ],
});

setInterval(() => {
  // keep the connection alive
  client.getConnection().send("[]");
}, 60000);
```

**Comment by quolpr** [comment]
@joanrieu hmm, I suspect it will not work for iOS. Also, you will need somehow to know that the server received that message to be 100% that the connection is alive. I also created separate issue for iOS https://github.com/trpc/trpc/issues/4078

**Comment by KATT** [comment]
Anyone wants to pick this up?
