### ISSUE TITLE
feat: Infer type of entire query

### ISSUE THREAD

**Issue by c-ehrlich** [trpc/trpc#3004]
### Describe the feature you'd like to request

This is a pattern that I would like to be able to do
```ts
const myQuery = trpc.router.procedure.useQuery(something); // or useInfiniteQuery
return <ChildComponent query={myQuery} />
```

But there doesn't seem to be a way to type this prop in the child component.

There are already `UseTRPCQueryResult` / `UseTRPCInfiniteQueryResult` types in the codebase which seem like they would be a first step to this, but they can't be imported.

### Describe the solution you'd like to see

`inferProcedure<AppRouter['router']['procedure']>`
might also need to take another generic for the error?

(naming could be anything)

### Desribe alternate solutions

Currently I just use other composition patterns, but this would be a nice option to have.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
It's a bit tricky because `useInfiniteQuery` is variadic* so unsure how this would look like. 

What's your reason of passing the full query and not only the `.data` ([which can be inferred easily](https://trpc.io/docs/v10/infer-types))?


* Unsure if variadic is the correct term - but basically its return type differs depending on what options you pass.

**Comment by KATT** [comment]
See #3005 for an example what I do
