### ISSUE TITLE
feat: Split `GetInferenceHelpers` in `Output` and `Input`

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3041]
### Describe the feature you'd like to request

Instead of having inference helpers that expose input and output together, I think we should make _two_ distinct inference helpers

Current:

```tsx
type RouterTypes = GetInferenceHelpers<AppRouter>;

type Post = RouterTypes['public']['post']['list']['output']['items'][number];
// Getting `items[number]` of `public.post.list.output`
// Hard to read
```

### Describe the solution you'd like to see

Better legibility:

```tsx
type RouterOutput = GetOutputInferenceHelpers<AppRouter>;
type RouterInput = GetInputInferenceHelpers<AppRouter>;


type Post = RouterOutput['public']['post']['list']['items'][number];
```

Split inference helpers in two.

### Desribe alternate solutions

We could also allow for this, which is even better legibility but will negatively affect TS perf on bigger routers.

#### Flattened path

```tsx
type RouterOutput = inferRouterOutput<AppRouter>;
type RouterInput = inferRouterInput<AppRouter>;


type Post = RouterOutput['public.post.list']['items'][number];
```

#### Fake representation of a router

@sachinraja brought up this idea as well:

```tsx
// could be a proxy for a readable error or we could just straight-up lie about the types

const routerOutputs = createRouterOutputTypes<AppRouter>();
const routerInputs = createRouterOutputTypes<AppRouter>();

type Post = typeof routerOutputs.post.byId
```

It's arguably a lot nicer for power users, but we do lie about the types.

### Additional information

Discussion about naming: https://github.com/trpc/trpc/discussions/2825

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by rhenriquez28** [comment]
Nothing to add, just wanted to say that I'd also be down to implement this feature if that's okay with y'all

**Comment by KATT** [comment]
> Nothing to add, just wanted to say that I'd also be down to implement this feature if that's okay with y'all

Feel free!

**Comment by rhenriquez28** [comment]
So, an update on this. The first solution was easy to do. The second one with the flattened path requires a lot more TS wizardry if it needs to be done like an object. I'm still intermediate on Type Challenges hahaha. However, I did manage to do it, but with a different approach, and wanted to see if you would consider it:

Instead of creating a mapped type with a lot of object key paths, why not just pass the path as a type parameter?

```ts
type RouterOutput<TPath extends string> = inferRouterOutput<AppRouter, TPath>;
type RouterInput<TPath extends string>  = inferRouterInput<AppRouter, TPath>;


type Post = RouterOutput<'public.post.list'>['items'][number];
``` 

**Pros**
- This approach behaves like a function: ``getRouterOutput(path: string) => ProcedureOutput``
- You know exactly when you start navigating through the output or input due to the distinction between <> and []
- It's a simpler type under the hood than what you would need to do to create the mapped type, which means it's easier to maintain.
- I know nothing about TS perf, but I would assume this would perform better than creating a complex mapped type with a lot of keys that could grow exponentially

**Cons**
- It requires the user to do more setup by making their type a generic

You can see my implementation in the draft PR I just created. Feel free to comment all you want about this haha.

Lastly, I didn't bother doing the third approach because although I think I have a very rough idea of how it would be done, I think someone with more knowledge of the codebase can do it better than me. Also, I like the consistency of everything being a type more instead of extracting a type from a value that, as you said, would be lying to you.

**Comment by sachinraja** [comment]
> I know nothing about TS perf, but I would assume this would perform better than creating a complex mapped type with a lot of keys that could grow exponentially

It wouldn't because TS defers evaluation of object properties. This is definitely worse perf-wise because it traverses the entire router to build the paths.

That being said, I do like your method. Just needs TS perf testing though.

**Comment by rhenriquez28** [comment]
>It wouldn't because TS defers evaluation of object properties.

Oh well, TIL. That being said, between just splitting the inference helpers and using the flattened path (with whichever approach you decide to go with), I very much prefer the flattened path. It's more readable and faster to work with.

**Comment by rhenriquez28** [comment]
So, I was going to update the docs for inferring types from the server, when I stumbled upon [this](https://trpc.io/docs/v10/infer-types#inference-helpers):

```ts
import type { inferProcedureInput, inferProcedureOutput } from '@trpc/server';
import type { AppRouter } from './server';

type PostCreateInput = inferProcedureInput<AppRouter['post']['create']>;
type PostCreateOutput = inferProcedureOutput<AppRouter['post']['create']>;
```

It seems, according to our own docs, that `GetInferenceHelpers` was created for "if you don't like the double-import from [`inferProcedureInput` and `inferProcedureOutput`]".

So, to me, `GetOutputInferenceHelpers` and `GetInputInferenceHelpers` seem redundant given that they use `inferProcedureInput` and `inferProcedureOutput` under the hood and we already export the `inferProcedureX` types.

So there are three options as I understand it:
1. Keep the `GetXInferenceHelpers` types while removing the export for `inferProcedureX` types
2. Remove `GetInferenceHelpers` and their subtypes and just export `inferProcedureX` types while refactoring the tests I just made
3. Leave thing as is.

I prefer number 2.

Thoughts @KATT @sachinraja ?

**Comment by sachinraja** [comment]
I would go with option 4:
- Keep the `GetXInferenceHelpers` and `inferProcedureX`
- Remove `GetInferenceHelpers`
- Change the docs so we show a clear preference for `GetXInferenceHelpers`

**Comment by rhenriquez28** [comment]
Alright, I'll do that. Although I'll not remove `GetInferenceHelpers` just not export it since I'm using it for the `GetXInferenceHelpers`. Do we keep exporting `inferProcedureX` types?

And, when it comes to the docs, do we completely ignore `inferProcedureX`, or do we say something like "you have two options that do the same thing: `GetXInferenceHelpers` and `inferProcedureX`. We strongly recommend using `GetXInferenceHelpers` though"

**Comment by sachinraja** [comment]
> Do we keep exporting inferProcedureX types?

Yes

> do we completely ignore inferProcedureX

I would completely ignore it

**Comment by rhenriquez28** [comment]
Perfect

**Comment by rhenriquez28** [comment]
PR is ready, although next-prisma-starter is failing deployment, but I don't know what's wrong
