### ISSUE TITLE
feat: move `trpc.something.getQueryKey` to a standalone function

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#3605]
### Describe the feature you'd like to request

Deprecate `.getQueryKey` from the magical chain. It's noisy and an edge-case where you need to use it.

<img width="333" alt="CleanShot 2023-01-11 at 23 13 40@2x" src="https://user-images.githubusercontent.com/459267/211929258-0002f973-0757-4322-add6-c20e5d92a851.png">

### Describe the solution you'd like to see

Introduce another way of accessing it like. Example:

Idea:

```ts
import { trpc } from '~/utils/trpc';
import { getQueryKey } from '@trpc/react-query';

function MyComponent() {
  const utils = trpc.useContext();

  const queryKey = utils.getQueryKey(t => t.post.byId('x'))
}
```

Only on the root?

```ts
import { trpc } from '~/utils/trpc';

function MyComponent() {
  const queryKey = trpc.getQueryKey(t => t.post.byId('x'))
}
```

### Describe alternate solutions

Above

### Additional information

- Deprecate in v10
- Delete in v11

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by juliusmarminge** [comment]
Moving to a standalone function would most likely require some additional work since in this example:

```ts
import { getQueryKey } from "@trpc/react-query";
import { trpc } from "~/utils/trpc";

const queryKey = getQueryKey(trpc.post.byId, input);
```

`trpc.post.byId` doesn't contain any useful information when passed like that - we could either add some meta-tag on the proxy without adding it to the types (so that it doesn't show up in autocomplete) or go for your second approach with the callback.

I vote to put it on the `trpc` object instead of utils so that it doesn't locks in to the react context

**Comment by KATT** [comment]
> `trpc.post.byId` doesn't contain any useful information when passed like that - we could either add some meta-tag on the proxy without adding it to the types (so that it doesn't show up in autocomplete) or go for your second approach with the callback.

I indeed think we need some meta tag that is hidden by the types, I should've added this to additional context lol

> 
> I vote to put it on the `trpc` object instead of utils so that it doesn't locks in to the react context

👍
