### ISSUE TITLE
Consider renaming `createSSGHelpers` to `createSSRHelpers`

### ISSUE THREAD

**Issue by kripod** [trpc/trpc#369]
The `createSSGHelpers` method of `@trpc/react` can be used for both SSG and SSR, and the former is just a special form of prerendering – "ahead-of-time SSR".

Also, I propose moving `@trpc/react/ssg` to `@trpc/react/ssr`.

**Comment by KATT** [comment]
It is intentional as I personally don't see much use of using those helpers for SSR rather than SSG since you can just turn on `{ ssr: true }`, I've never liked `getServerSideProps` myself as it always adds a delay to the route change.

Did you know that even with SSR you can take advantage of Vercel's edge cache?

https://trpc.io/docs/caching#app-caching

Read the twitter thread that's linked there. As long as each dynamic page has been visited at least once since the last deploy and you have cache headers you are able to get it statically delivered.
