### ISSUE TITLE
feat: disable output validation in production

### ISSUE THREAD

**Issue by romeerez** [trpc/trpc#4282]
### Describe the feature you'd like to request

I'd like to use `output`, but don't find it useful in production env.

`output` is useful because:
- we can write integration tests where we test only the logic, and the shape of the data will be validated by the `output` function.
- we can see what we expect to return from the route, prevent returning wrong output with a TS error.
- TS is barely breathing in some cases because it's too much for it to infer. Specifying `output` could help TS with this.

But I'd like the production server to not spend time and resources on validating output because it was already validated in dev and in CI.

### Describe the solution you'd like to see

`create` function could accept `validateOutput` boolean option in such a way:

```ts
initTRPC.create({
  validateOutput: process.env.NODE_ENV !== 'production',
});
```

### Describe alternate solutions

Let me know if there is some workaround, I'm not aware of them.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by KATT** [comment]
This should work as a workaround:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzsAdsGAVASgBQMJwC+cAZlBCHAOQACMUYAxgPQDOAplAG6dUDcAKFCRYiOAC8ipcpSriIAE35Dw0eEkZR2AQxjts+HOQAeATzwAbYOxQwANHAAWMGGABCuxo4AyqANZSZBTUdAwsjFY2MMoCjBAorOpg5IzsCgCuWg7k6XpQxAC8yGiYuHgAdJo6egAUAJQCAiTpKIwwwPFwCuxcAPIoFqYAyl7sINoAPBgjjmPacOzGeigKrBLlAFqKGKZg7AB8Nayj4wBccNMn2nWIAnDIJHA1yRCprKzlNlzlAHK9ACIAUQA+oCfgA1OAFaHUF4ZNodFBUG4IO73OBaGCZFDrbQoUz1ODaNYtPwoCAAdxxxIuMzmgnuhDRmOxcGOs3GgiZsXiiTZVyhXR6-UGdPGNXE5W0UCg2gJkogACMAFbsNo1BDABTnSWJKCoADm9UIdVNgh5CXg2jAYCwEFynEFOTyGrR6Q4UF8iXOL1SGS05XtrlyRyudXKAEd0pwCcTTK0njcCvtbuiMewsVAcQBtNFp1FptNa85UACMVDsefRTLTAF00SbKybzcxmHBAcYRPAYLt2Big46e3s2cADShdJl2JXW3A-hg4DBZv2HVBkDAOBYSOUBIsuwve3AAII2u0rwVD9gQR7W20DqDmxpxS0LsKCqq6fRlIwQMyWay2CZj1vFdDgLOArBQPxWHOXM02cVwPBgLxfEg11CzgTILBLeCwFOVsLFebQLEcCBvQAZgABioisq0bNFaybOpzSfPktFYdILHgIptApbR0BfJhyndTgvRgSNoygAkGhnNMAD0AH4gA


I don't know if I want to add this to tRPC as I wouldn't recommend this as a legit workaround since there's a risk that you might leak extra information that zod normally would strip out.

Here's a basic example where TypeScript wouldn't complain, your dev environment would strip it but in prod you'd leak credentials: https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATlAvFA3gKClAlgEwC4o5hFcA7AcwG5soIBbAQ1wBtjTzq6BfTTADMArhQDGwXAHsKUKhGDwkACgCUxJciw4xM0lGEJkabTjxEoAIgCMlgDT0cTVhyvAIpAAIQAHs0ZgbBAAdLqM9o5QYMxwcADuUogWAORgnrFxAAxJyfT89IgKwoiyhkh8mEA

**Comment by KATT** [comment]
Feels like premature optimization. Fix it when it's a problem instead of risking shooting yourself in the foot

**Comment by romeerez** [comment]
It's not a premature optimization. That's a good point about leaking data, and I realized that my suggestion is not enough: to validate in dev and test mode and then relax in production. Because `zod` by default is stripping undeclared fields without error, and then it can become a leak in production.

Ideally, in dev and test mode, it should be possible to make it throw when the response has an undeclared field, and only then it's safe to turn off the output validations in production.

**Comment by KATT** [comment]
Not sold on this as it will give a false sense of safety, but if you make a PR, we'll consider it

**Comment by romeerez** [comment]
This feature indeed has no community interest so not worth implementing. I asked people what they think about validating the response in general, and it seems nobody does it, including tRPC docs and example apps.
