### ISSUE TITLE
feat: Preserve typing of inputParser / output parser

### ISSUE THREAD

**Issue by tonyxiao** [trpc/trpc#4295]
### Describe the feature you'd like to request

I'd like to re-use the input parsers elsewhere in the code (to auto generate forms) but right now the input parser's type themselves are lost therefore making it much harder to re-use the schemas. 

### Describe the solution you'd like to see

Maybe we can leverage `satisfies` in ts 5.0 to make it so that each procedure retains the actual types of its input / output parsers rather than simply casting everything to `Parser`

### Describe alternate solutions

My current workaround
<img width="674" alt="image" src="https://user-images.githubusercontent.com/696842/235767444-d0f599e4-c143-4960-8a44-59f1d3ac39c6.png">

### Additional information

Happy to contrib PR but would need some pointers on direction

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by Nick-Lucas** [comment]
What’s wrong with defining your input in a common library and importing it directly for use elsewhere? This is quite common when we need Zod types for form validation as well as input validation on submit

**Comment by tonyxiao** [comment]
Quite a bit of boiler plate by maintaining a large amount of variables, that simply mirror the structure of the router itself

**Comment by Nick-Lucas** [comment]
So to avoid confusion, if all you need is get the typescript type for compile-time checks, we have docs for this: https://trpc.io/docs/client/infer-types

If what you need is the Zod schema in order to generate forms, you need to import the Zod schema into the client properly because that's real code that needs to be bundled into the client, not just the TS types. tRPC isn't concerned with giving you runtime reflection of schemas because you're in control of the schemas and can import them directly instead.

You could write a special procedure which enumerates the type information from Zod, but that's a lot more effort than just importing the type from a common library

**Comment by tonyxiao** [comment]
Fair enough re trpc scope, and probably best practice to avoid polluting client /increasing bundle size with server code anyways . Though to clarify I'm specifically referring to the fact that the `adminCreateConnectToken` below is repeated twice. 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/696842/235940461-acce669c-1a95-4fed-93ef-9e52786b1e51.png">

**Comment by tonyxiao** [comment]
I think maybe the real request here is being able to separate out the definition of schema from the implementation of procedures in trpc. Right now they are coupled in one place and therefore not safe for client to easily import the schema.

**Comment by Nick-Lucas** [comment]
I am going to close this issue just because it's not something we're likely to do any work on, since the ecosystem provides simpler solutions already. However, please feel free to either open a Discussion or come over to our Discord where we have Help channels (most people do this, it's easier to have open discussions there)
