### ISSUE TITLE
chore: refactor our testing 

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#4465]
### Describe the feature you'd like to request

Currently, we do most of our tests in `/package/tests/**`

Problems:

* This is fine for most cases, but sometimes we want contextual test next to the files themselves
* We have a bunch of testing deps in our root `/package.json`

### Describe the solution you'd like to see

We probably want our testing to be a private library that other packages can depend on so we can have all our testing libs in 1 place.

Not sure what I want, but what we have now is very messy. Need to look at how other big OSS-libs with multiple packages do their testing

Maybe?:

* we have a private testing package in `packages/testlib` just for the deps and the utils that all packages have in a `devDependencies`
* we have a `packages/tests` that does the actual integration testing

### Describe alternate solutions

not doing it

### Additional information

It might be a painful thing to do since we have both `main` and `next` that we wanna keep in sync. Feels like an annoying conflict resolution

<sub>From [SyncLinear.com](https://synclinear.com) | [T-87](https://linear.app/trpc/issue/T-87/chore-refactor-our-testing)</sub>

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4465">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4465/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4465/pledge.svg">
</picture>
</a>

**Comment by il3ven** [comment]
I'll like to work on this. My recommendation is that all packages should maintain the testing dependencies themselves. Otherwise npm/linters may complain that the dependency is not found. As it will not be mentioned in package.json of the package that needs to be tested but rather in the package.json of `testLib`.

We can still have a `packages/testLib` package for utils.

If you want to create `testLib` package for shared dependencies then my recommendation is to re-export all test libraries from `testLib` and import them from `testLib` like below:

```js
// packages/testLib
export { * } from '@testing-library/dom'

// packages/server
import { getByLabelText } from 'testLib/@testing-library/dom'
```

[Vitest](https://github.com/vitest-dev/vitest/tree/main/test) for their repo has created a corresponding *test* package for every core package. For example, for `pacakges/ui` package they have a `tests/ui` package. We can do this too but in my opinion it is not needed until we have a lot of tests. We can keep the tests along with the source code.

EDIT: @KATT saw your draft PR. Is this issue still available?

**Comment by KATT** [comment]
Hey @il3ven, yeah, this is still available! I had a stab, and hoped I could fix it quickly, but I couldn't.

Feel free to play with it. Make sure not to move too many files around because we'll get hellish merge conflicts since we're maintaining the [`next`](https://github.com/trpc/trpc/tree/next)-branch too

**Comment by Sambit003** [comment]
@KATT is this issue still open or closed?

**Comment by KATT** [comment]
Open
