### ISSUE TITLE
feat: Angular connector

### ISSUE THREAD

**Issue by Akxe** [trpc/trpc#4944]
### Describe the feature you'd like to request

I would love to seamlessly use tRPC in Angular.to use tRPC in Angular seamlessly.

### Describe the solution you'd like to see

An official tRPC connector with all the features and whistles; comparable to react query.

### Describe alternate solutions

Vanilla solution, or follow some of the few tutorials out there.

### Additional information

I am willing to help. I am quite adept in Angular and RXJS, but I am very new to tRPC. I would love to help and be helped on this feature implementation.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/4944">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/4944/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/4944/pledge.svg">
</picture>
</a>

**Comment by Nick-Lucas** [comment]
Hi Adam,

We've discussed Angular support in the past and because none of the core team use it, it's not something we're willing or able to support 1st class as an official package. That said we'd be happy to support any community efforts to understand how to write integrations from the tRPC side.

You can join us on discord where asking questions for guidance is a little easier: https://discord.com/invite/trpc-867764511159091230
