### ISSUE TITLE
feat(fastify): add `onError`-callback

### ISSUE THREAD

**Issue by Lilja** [trpc/trpc#5126]
### Provide environment information

```  
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @tanstack/react-query: ^4.18.0 => 4.36.1 
    @trpc/client: ^10.44.1 => 10.44.1 
    @trpc/next: ^10.44.1 => 10.44.1 
    @trpc/react-query: ^10.44.1 => 10.44.1 
    @trpc/server: ^10.44.1 => 10.44.1 
    next: ^14.0.1 => 14.0.3 
    react: ^18.2.0 => 18.2.0 
    typescript: ^5.1.3 => 5.3.2
```

### Describe the bug

Creating an `onError` with `trpcNext.createNextApiHandler` works great. Not so much for the fastify plugin.
![image](https://github.com/trpc/trpc/assets/6134511/e97a69db-b406-4605-96b0-7cb22af4584e)

### Link to reproduction

https://stackblitz.com/edit/github-zqvhhh?file=src%2Fpages%2Fapi%2Ftrpc%2F%5Btrpc%5D.ts

### To reproduce

Install the dependencies and you should see squiggly errors for the fastify `onError` adapter

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5126">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5126/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5126/pledge.svg">
</picture>
</a>

**Comment by achrafl0** [comment]
> I added a `satisfies` keyword to the `trpcOptions` object. I wonder if it's more of an issue with fastify and its plugin system? !

Hey @Lilja , I tried taking a look at this, I found that typing the `fastifyTRPCPlugin` as `FastifyPluginCallback<FastifyTRPCPluginOptions<TRouter>>` ( or using satisfies ) will make the error disappear, but the issue is getting that generic `TRouter` in the typing ( or the satisfies ) and ofc using a default value like `AppRouter` would be against the principle of trpc 

<img width="655" alt="image" src="https://github.com/trpc/trpc/assets/63306573/6b7af7af-4365-42b2-8ac1-494c40a8135f">

I even tried using the `fastify-plugin` helper library 
But I could not get it to work 😅

<img width="800" alt="image" src="https://github.com/trpc/trpc/assets/63306573/3e5a0cda-fd50-41a2-a625-bdbaee5be627">

So I think your intuition is correct and maybe it's more on the side of the inference of the typing of fastify's plugins !

**Comment by KATT** [comment]
Feel free to make a pr, I don't use the fastify plugin myself so I won't add it (unless someone pays me 😅)

**Comment by Lilja** [comment]
Cool! Later, I tried to do 
```typescript
server.register(fastifyTRPCPlugin<AppRouter>, {
 prefix: 'whatever',
  trpcOptions: {
    router: appRouter,
    createContext: () => ({}),
    onError(opts) {
      opts.ctx;
    },
  },
)

```

Which also seems to work.
![image](https://github.com/trpc/trpc/assets/6134511/45f1c55d-1797-48c7-9c78-f2775ba48d51)
