### ISSUE TITLE
docs: Provide examples using tRPC with Next.js app router

### ISSUE THREAD

**Issue by Pavan-Rajesh** [trpc/trpc#5277]
### Area of Improvement

Only tRPC using page Router in Next.js are present in your documentation. Please Provide Examples for tRPC using Next.js app Router 

### Link to related docs

https://trpc.io/docs/client/nextjs/setup

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing the suggested changes!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/trpc/trpc/issues/5277">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/trpc/trpc/issues/5277/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/trpc/trpc/issues/5277/pledge.svg">
</picture>
</a>

**Comment by maryamkhan14** [comment]
Seconding this! It's been hard to find any authoritative sources on TRPC usage with the App Router.

**Comment by oeuvars** [comment]
Hey @maryamkhan14, you can refer to this video https://www.youtube.com/watch?v=qCLV0Iaq9zU to set up trpc with Next.js App router, also you can go to my repositories and check the *Pestile* repo which is set up using Next.js app router with Trpc.

**Comment by ShashwatPS** [comment]
Hey i would like to add a setup structure for the appRouter in Nextjs. Attached a repo for reference to set it up.

https://github.com/ShashwatPS/Trpc_CraveFeed/tree/f7e28e314487b0b528a404f68f92395b5acda818/cravefeed

**Comment by Pavan-Rajesh** [comment]
This can help you and I will be writing a blog article by today 

This is minimalist example and very easy to understand

https://github.com/Pavan-Rajesh/tRPC-Nextjs-App-Router-Minimal.git

**Comment by jeffrey-computers** [comment]
Bump. Also relates to https://github.com/trpc/trpc/issues/5625

I can find _no_ explanation _anywhere_  for how to cache trpc endpoints when using the NextJS App Router

**Comment by iduuck** [comment]
@jeffrey-computers I think Nick Lucas (don't want to ping him here) mentioned on twitter, that the documentation is not being updated until v11 is released: https://x.com/NckLcs/status/1788275302340100304

**Comment by KATT** [comment]
I think the closest thing to what we want to recommend if you have a monolithic app is to use `@trpc/server` as a slim data layer on top of your backend - you can see that here https://github.com/trpc/examples-next-app-dir/tree/main/src/app/posts

If you're running a separate service for your api layer, it'll likely look quite different. If you are making an SPA, it looks more like how it always has. 

It's hard to know what people actually expect and how people want to use trpc for in this new world where React, since RSC and server actions, solves a lot of the things that trpc was created for.
