### ISSUE TITLE
Adding lockfiles to examples

### ISSUE THREAD

**Issue by KATT** [trpc/trpc#94]
- `examples/*` doesn't have lockfiles right now as they're part of the monorepo
- this might make the vercel deployment randomly fail if someone publishes a bad build of the 10^100 sub-deps of next (as shown yesterday in https://github.com/trpc/trpc/pull/91#issuecomment-781434382)
- would be nice if they had lockfiles but not sure how to make it happen in the yarn workspace

**Comment by emilbryggare** [comment]
@KATT: What are the benefits of having the examples as part of the Yarn Workspace?

I just modified one of the examples in a PR (#1552), and it modified the root yarn.lock which does not seem ideal as I've not really touched any real "packages".

My suggestion is to just remove the examples from the yarn workspace package list.

```
  "workspaces": {
    "packages": [
      "packages/*",
      "examples/*", <-- Remove these
      "examples/.wip/*" <-- Remove these
    ],
    "nohoist": [
      "**/@prisma",
      "**/@prisma/**"
    ]
  }
```

The examples will then mind their own business and receive their own lockfiles. What am I missing?

**Comment by sachinraja** [comment]
Not sure if it's also a problem here, but I've had issues with trying to detach the examples when using React in my monorepos. Since the `@trpc` packages depend on React as a dev dependency, it is installed in `node_modules` and webpack may resolve React from there. But it is also installed as a peer dependency and webpack also bundles that. Since you can't have two versions of React, that will break it. Related issue I made for pnpm: https://github.com/pnpm/pnpm/discussions/3833. Also yarn won't be able to link the example packages to the actual `@trpc` packages in the monorepo automatically. We'll have to use a special specifier like `file:`.

**Comment by KATT** [comment]
Closing for now, it's rarely a problem.

**Comment by iduuck** [comment]
@KATT pnpm has a utility for this name [`@pnpm/make-dedicated-lockfile`](https://github.com/pnpm/pnpm/tree/main/packages/make-dedicated-lockfile), which however is deprecated, because of the `pnpm deploy` command. However, I don't know, how to actually utilise this.

**Comment by QuiiBz** [comment]
The monorepo moved to pnpm a few months ago, and there's an option that might fix this issue: [`shared-workspace-lockfile`](https://pnpm.io/npmrc#shared-workspace-lockfile).

It's `true` by default, but when set to `false` each package in the monorepo will have its own `pnpm-lock.yaml` (not only examples, but ALL packages). Not sure if it's a good idea or not, we might need to test it a bit more.

Note that this option has some drawbacks, namely:
- Slower installations
- More changes in code review

**Comment by nawed2611** [comment]
Hey, can I work on this?

**Comment by KATT** [comment]
Feel free to work at this. Seems like @QuiiBz has a good idea how to solve it, we can try that

**Comment by nawed2611** [comment]
From what I understand, adding `shared-workspace-lockfile: false` in `pnpm-workspace.yaml` would work ig?
